# File: .github/workflows/yt-dlp-daily.yml

name: Daily yt-dlp rebuild

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'  # Daily at 03:00 UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Authenticate to Google Cloud using the service account key JSON
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 363.0.0'

      # Trigger Cloud Build
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml .
